Add support for backfill releases

diff --git a/squid-release-management/gh-release b/squid-release-management/gh-release
--- a/squid-release-management/gh-release
+++ b/squid-release-management/gh-release
@@ -4,10 +4,11 @@ set -euo pipefail
 repo=""
 origin="origin"
 upstream="upstream"
+backfill=""
 
 # test for tools
-SED=`which gsed` ; SED=${SED:-sed}
-FGREP=`which fgrep`; FGREP=${FGREP:-fgrep}
+SED=`which gsed` ; SED="${SED:-sed}"
+FGREP=`which fgrep`; FGREP="${FGREP:-fgrep}"
 
 po2html=`which po2html`
 if test -z "$po2html" ; then
@@ -23,11 +24,15 @@ fi
 usage() {
 cat <<_EOF
 use:
- $0 [options]<new version> <old version>
+ $0 [options] <new version> <old version>
  options:
-   -R Github-repo
-   -o origin
-   -u upstream
+   -R <github-repo> to use for PRs
+   -o <origin>: (git) remote repository for pushing PR branches
+                default "origin"
+   -u <upstream>: (git) remote repository with public sources to use
+                  default "upstream"
+   -b : this is a backfill. Create a release for <new version> using
+        preexisting tags.
 
 If no ChangeLog entry exists for the new version, prepares one
 and helps prepare it for merge.
@@ -39,12 +44,55 @@ release artifiacts, and finally tag it with RELEASE_<NEW_RELEASE>
 _EOF
 }
 
-while getopts "hR:o:u:" optchar ; do
+package_release() {
+# actually prep the release
+
+    git clean -fdx
+    git checkout -b $release_branch $current_branch
+    ./bootstrap.sh
+    $SED -i~ "s@${new_version}-VCS@${new_version}@" configure.ac && rm configure.ac~
+    $SED -i~ "s@${new_version}-VCS@${new_version}@" configure && rm configure~
+    $SED -i~ "s@squid_curtime@${release_time}@" include/version.h && rm include/version.h~
+    rm libltdl/config-h.in~ libltdl/configure~
+    git add -f '**' # ignore .gitignore
+
+    ./configure --silent --enable-translation
+    make dist-all
+    make distclean #TODO: is this to be done?
+    git add -u
+# TODO: add artifacts (e.g. configure)
+    git add errors/
+    git commit -m "Squid v$new_version release"
+    git tag "$release_tag"
+
+# prep changelog
+    export new_version
+    awk "/^Changes in squid-${new_version}/{flag=1} /^$/{flag=0} flag" ChangeLog >$release_changelog_file
+    local push_tag
+    if [ -z "$backfill" ] ; then push_tag="$new_tag" ; fi
+    echo "time for pushing. Please run (when ready): "
+    echo "git push $upstream $release_branch $push_tag $release_tag"
+    echo "gh $repo release create $release_tag -F $release_changelog_file --title "v${new_version}" squid-${new_version}.tar.*"
+}
+
+# argument: a tag. Returns 0 if the tag exists, 1 if it doesn't
+have_tag() {
+    git tag -l "$1" | $FGREP -q "$1"
+    return $?
+}
+
+have_branch() {
+    git branch -l "$1" | $FGREP -q "$1"
+    return $?
+}
+
+while getopts "hR:o:u:b" optchar ; do
     case "${optchar}" in
     h) usage; exit 0;;
     R) repo="-R ${OPTARG}";;
     o) origin="$OPTARG";;
     u) upstream="$OPTARG";;
+    b) backfill="yes";;
     -) break;;
     esac
 done
@@ -55,8 +103,8 @@ if [ $# -lt 2 ]; then
     exit 2
 fi
 
-new_version=$1
-old_version=$2
+new_version="$1"
+old_version="$2"
 
 new_tag=SQUID_`echo $new_version | tr . _`
 old_tag=SQUID_`echo $old_version | tr . _`
@@ -74,32 +122,38 @@ echo "new: $new_tag old: $old_tag"
 echo "repository: $repo"
 
 # check that old tag exists
-if ! git tag -l $old_tag | $FGREP -q $old_tag ; then
+if ! have_tag "$old_tag" ; then
     echo "could not find tag $old_tag"
     usage
     exit 2
 fi
 
-# check that new tag does not exist
-if git tag -l $new_tag | $FGREP -q $new_tag ; then
-    echo "tag $new_tag is already defined"
-    echo "If it shouldn't, use:"
-    echo "git tag -d $new_tag $release_tag"
-    exit 2
+if [ -n "$backfill" ]; then
+    git reset --hard "$new_tag"
+    git clean -fdx
+    git branch -D "$release_branch" || true
+    git tag -d "$release_tag" || true
+    git push -d origin "$release_branch" "$release_tag" || true
+    # TODO: here
+    package_release
+    exit 0
 fi
+
 # check that release tag does not exist
-if git tag -l $release_tag | $FGREP -q $release_tag ; then
+if have_tag "$release_tag" ; then
     echo "tag $release_tag is already defined"
     echo "If it shouldn't, use:"
     echo "git tag -d $release_tag"
+    echo "If you also want to delete the anchor tag, then"
+    echo "git tag -d $new_tag"
     exit 2
 fi
 
 # if the ChangeLog is not ready, prepare one and bail
 if ! fgrep -q "Changes in squid-${new_version}" ChangeLog; then
-    if git branch -l $release_prep_branch | $FGREP -q $release_prep_branch ; then 
-        git branch -D $release_prep_branch
-        git push -d $origin $release_prep_branch || true # ignore errors
+    if have_branch "$release_prep_branch" ; then
+        git branch -D "$release_prep_branch"
+        git push -d "$origin" "$release_prep_branch" || true # ignore errors
     fi
     echo "Please prepare the ChangeLog and remove this line" >>$tmp_changelog_file
     echo "Changes in squid-${new_version} (`date '+%d %b %Y'`)" >>$tmp_changelog_file
@@ -111,17 +165,25 @@ if ! fgrep -q "Changes in squid-${new_version}" ChangeLog; then
     git checkout -b $release_prep_branch $current_branch
     git add ChangeLog
     git commit -m "Prep for v$new_version"
-    git push $origin # TODO: should we make a parameter?
+    git push $origin
     gh $repo pr create --base $current_branch --title "Prep for v$new_version"
     git switch $current_branch
+
+    echo
+    echo "now merge the ChangeLog PR and then run again"
+    echo "$0 $@"
     exit 0
 fi
 
-## at the end
+
+# TODO: if have_tag $new_release, then get to that point in time and
+#       skip fixing changelog
 # check that the release in configure.ac is what we expect it to be
-if ! $FGREP -q "AC_INIT([Squid Web Proxy],[${old_version}-VCS],[https://bugs.squid-cache.org/],[squid])" configure.ac ; then
-    echo "old version $old_version not found in configure.ac"
-    exit 2
+if ! $FGREP -q "AC_INIT([Squid Web Proxy],[${new_version}-VCS],[https://bugs.squid-cache.org/],[squid])" configure.ac ; then
+    if ! $FGREP -q "AC_INIT([Squid Web Proxy],[${old_version}-VCS],[https://bugs.squid-cache.org/],[squid])" configure.ac ; then
+        echo "old version $old_version not found in configure.ac"
+        exit 2
+    fi
 fi
 
 # update release version in configure.ac
@@ -132,30 +194,5 @@ git commit -m "v$new_version"
 git tag $new_tag
 
 git branch -D $release_branch
-git checkout -b $release_branch $current_branch
 
-# actually prep the release
-
-git clean -fdx
-./bootstrap.sh
-$SED -i~ "s@${new_version}-VCS@${new_version}@" configure.ac && rm configure.ac~
-$SED -i~ "s@${new_version}-VCS@${new_version}@" configure && rm configure~
-$SED -i~ "s@squid_curtime@${release_time}@" include/version.h && rm include/version.h~
-rm libltdl/config-h.in~ libltdl/configure~
-git add -f '**' # ignore .gitignore
-
-./configure --silent --enable-translation
-make dist-all
-make distclean #TODO: is this to be done?
-git add -u
-# TODO: add artifacts (e.g. configure)
-git add errors/
-git commit -m "Squid v$new_version release"
-git tag $release_tag
-
-# prep changelog
-export new_version
-awk "/^Changes in squid-${new_version}/{flag=1} /^$/{flag=0} flag" ChangeLog >$release_changelog_file
-echo "time for pushing. Please run (when ready): "
-echo "git push $upstream $release_branch $new_tag $release_tag"
-echo "gh $repo release create $release_tag -F $release_changelog_file --title "v${new_version}" squid-${new_version}.tar.*"
+package_release
